version: '3.9'

services:
  db:
    image: postgres
    platform: linux/x86_64
    container_name: labs-examinations-api
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=labs
    ports:
      - '54320:5432'
